object Versions {
    // App
    const val versionName               = "1.0"
    const val versionCode               = 2
    // Android
    const val minSdk                    = 22
    const val compileSdk                = 34
    const val jvmTarget                 = "17"
    const val kotlinCompilerExtension   = "1.5.6"
    // Libraries versions
    const val gradle                    = "8.2.0"
    const val kotlin                    = "1.9.21"
    const val buildKonfig               = "0.15.1"
    const val androidXCore              = "1.10.0"
    const val androidXWorkRuntime       = "2.7.1"
    const val constraintLayout          = "2.1.3"
    const val viewBinding               = "8.1.2"
    const val onetrustSDK               = "6.26.0.0"
    const val appCompat                 = "1.4.1"
    const val ktxCore                   = "1.3.1"
    const val material                  = "1.5.0"
    const val compose                   = "1.5.1"
    const val activityCompose           = "1.7.2"
    const val lifecycle                 = "2.4.0"
    const val appStartUp                = "1.1.0"
    const val kotlinAtomicity           = "0.20.2"
    const val coroutines                = "1.7.2"
    const val kotlinxDatetime           = "0.4.1"
    const val logback                   = "1.2.5"
    const val ktor                      = "2.3.6"
    const val ktorfit                   = "1.11.1"
    const val ksp                       = "$kotlin-1.0.15"
    const val realm                     = "1.11.0"
    const val chucker                   = "3.5.2"
    const val kotlinSerialization       = "1.6.0"
    const val okhttpLoggingInterceptor  = "4.10.0"
    const val fragmentX                 = "1.4.1"
    const val activityX                 = "1.4.0"
    const val testRunner                = "1.2.0"
    const val securityCrypto            = "1.1.0-alpha03"
    const val dependencyUpdatesCheck    = "1.5.0"
    const val hyperion                  = "0.9.34"
    const val utiq                      = "0.1.17"
    const val funnelConnect             = "0.1.17"
}
